## This configuration was generated by terraform-provider-oci
resource oci_database_pluggable_database "DB001007_pdb1" {
  container_database_id = "ocid1.dbsystem.oc1.ap-mumbai-1.anrg6ljr4twgpnaa45yt44btbtxvfgsrslbnkimovu5hi37qqaw2xcphm2da"
  defined_tags = {
  }
  freeform_tags = {
  }
  pdb_admin_password ="DBsggT-#T56t"
  pdb_name = "DB001007_pdb1"
  #should_pdb_admin_account_be_locked = <<Optional value not found in discovery>>
  tde_wallet_password = "DBsggT-#T56t"
}

