## This configuration was generated by terraform-provider-oci
resource oci_database_pluggable_database "DB001011_pdb1" {
  container_database_id = "ocid1.database.oc1.ap-mumbai-1.anrg6ljr4twgpnaalto23gx563y5qzgg34ysy6oqeuu2tnzt7rcj3sjeaska"
  defined_tags = {
  }
  freeform_tags = {
  }
  pdb_admin_password ="DBsggT-#T56t"
  pdb_name = "DB001011_pdb1"
  #should_pdb_admin_account_be_locked = <<Optional value not found in discovery>>
  tde_wallet_password = "DBsggT-#T56t"
}

