## This configuration was generated by terraform-provider-oci

resource oci_database_db_system "CreateDBSystem" {
  availability_domain = "HHnh:AP-MUMBAI-1-AD-1"
  #backup_network_nsg_ids = <<Optional value not found in discovery>>
  #backup_subnet_id = <<Optional value not found in discovery>>
  #cluster_name = <<Optional value not found in discovery>>
  compartment_id          = var.compartment_ocid
  cpu_core_count          = "1"
  data_storage_percentage = "80"
  data_storage_size_in_gb = "256"
  database_edition        = "ENTERPRISE_EDITION_HIGH_PERFORMANCE"
  db_home {
    #create_async = <<Optional value not found in discovery>>
    database {
      admin_password = "DBsggT-#T56t" #Required attribute not found in discovery, placeholder value set to avoid plan failure
      #backup_id = <<Optional value not found in discovery>>
      #backup_tde_password = <<Optional value not found in discovery>>
      character_set = "AL32UTF8"
      #database_id = <<Optional value not found in discovery>>
      #database_software_image_id = <<Optional value not found in discovery>>
      db_backup_config {
        auto_backup_enabled = "false"
        auto_backup_window  = ""
        #recovery_window_in_days = <<Optional value not found in discovery>>
      }
      #db_domain = <<Optional value not found in discovery>>
      db_name     = "DB001006"
      db_workload = "OLTP"
      defined_tags = {
        "Oracle-Tags.CreatedBy" = "sureshanair@gmail.com"
       # "Oracle-Tags.CreatedOn" = "2021-12-22T15:54:17.515Z"
      }
      freeform_tags = {
      }
      ncharacter_set = "AL16UTF16"
      #pdb_name = <<Optional value not found in discovery>>
      #tde_wallet_password = <<Optional value not found in discovery>>
      #time_stamp_for_point_in_time_recovery = <<Optional value not found in discovery>>
    }
    #database_software_image_id = <<Optional value not found in discovery>>
    db_version = "19.12.0.0"
    #defined_tags = <<Optional value not found in discovery>>
    display_name = "dbhome20211222155418"
    freeform_tags = {
    }
  }
  db_system_options {
    storage_management = "ASM"
  }
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "sureshanair@gmail.com"
    #"Oracle-Tags.CreatedOn" = "2021-12-22T15:54:16.552Z"
  }
  disk_redundancy = "HIGH"
  display_name    = "DB001006"
  domain          = "sub12220604390.dbvcn1.oraclevcn.com"
  fault_domains = [
    "FAULT-DOMAIN-1",
  ]
  freeform_tags = {
  }
  hostname = "db001006"
  #kms_key_id = <<Optional value not found in discovery>>
  #kms_key_version_id = <<Optional value not found in discovery>>
  license_model = "LICENSE_INCLUDED"
  #maintenance_window_details = <<Optional value not found in discovery>>
  node_count = "1"
  #nsg_ids = <<Optional value not found in discovery>>
  #private_ip = <<Optional value not found in discovery>>
  shape  = "VM.Standard2.1"
  source = "NONE"
  #source_db_system_id = <<Optional value not found in discovery>>
  #sparse_diskgroup = <<Optional value not found in discovery>>
  ssh_public_keys = [
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9Kqy2B+0gEx4sPslc9/6bYFcNUo4FQOil83Rn/ikOr8W+r5TTDpmz1rzj15fjAFkg1XxWjgT/fRh1CwDT+JbzkDaCO0ws5U3Pr8T4Gt38JFehPZ9WkysB4PkrZsaY0Ac0jnEa+yh2j2k0au2lJfoOZtxYu8n82kugRRSVyrO8vkGMHI6xIAExjC77tuAREOj760PIT8s+URyx5joEH+NJ6cTR8oBNv5iyYmz1O1aD1tbVYXqQHU6pWntYhE5yIK0B+lOpUNHHYEOclR3c0wVxkoJjBHzIp4U/LCrmX9NR9Du6L9b1JDMhg4KxGoRIujUyht4VkoeGJg0G+VCQm61t rsa-key-20211222",
  ]
  subnet_id = "ocid1.subnet.oc1.ap-mumbai-1.aaaaaaaaigrv6xfpnkpd3p76lqnyvkm66v3kfwcwhz7h23kehxgowchkopka"
  time_zone = "UTC"

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [db_home[0].database[0].admin_password]
  }
}

resource oci_database_pluggable_database "DB001006_pdb1" {
  container_database_id = "ocid1.database.oc1.ap-mumbai-1.anrg6ljr4twgpnaalto23gx563y5qzgg34ysy6oqeuu2tnzt7rcj3sjeaska"
  defined_tags = {
  }
  freeform_tags = {
  }
  pdb_admin_password ="DBsggT-#T56t"
  pdb_name = "DB001006_pdb1"
  #should_pdb_admin_account_be_locked = <<Optional value not found in discovery>>
  tde_wallet_password = "DBsggT-#T56t"
}

